참고자료


https://www.youtube.com/playlist?list=PLX2gX-ftPVXU3oUFNATxGXY90AULiqnWT


https://nbviewer.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/table_of_contents.ipynb

In [42]:
import numpy as np

# Initialize (Design)

### Design the State Matrix

In [43]:
# Design State Matrix
x = np.array([[10.0],
              [4.5]])
x

array([[10. ],
       [ 4.5]])

### Design the Process Covariance Matrix

The position and velocities are correlated.

But how correlated are they for a dog? we have no idea.

As we will see the filter computes this for us, so we initialize the covariances to zero.

Of course, if we know the covariances we should use them.

In [44]:
# Design Process Covariance Matrix
P = np.diag([500., 49.])
P

array([[500.,   0.],
       [  0.,  49.]])

### Design the State Transition Matrix

In [45]:
dt = 0.1
F = np.array([[1., dt],
              [0, 1.]])
F

array([[1. , 0.1],
       [0. , 1. ]])

### Predict without any update

In [46]:
from filterpy.kalman import predict

for _ in range(4):
    x, P = predict(x=x, P=P, F=F, Q=0)
    print(f'x = {x}')


x = [[10.45]
 [ 4.5 ]]
x = [[10.9]
 [ 4.5]]
x = [[11.35]
 [ 4.5 ]]
x = [[11.8]
 [ 4.5]]


### Design Process Noise

In [47]:
from filterpy.common import Q_discrete_white_noise
Q = Q_discrete_white_noise(dim=2, dt=1., var=2.35)
Q

array([[0.5875, 1.175 ],
       [1.175 , 2.35  ]])

### Design the Control Function

In [50]:
B = 0.  # Assume that there are no control inputs
u = 0
x, P = predict(x, P, F, Q, B, u)
print('x =', x)
print('P =', P)

x = [[13.15]
 [ 4.5 ]]
P = [[526.595  38.53 ]
 [ 38.53   56.05 ]]


### Prediction: Summary

Your job as a designer is to specify the matrices for

- x, P: the state and covariance
- F, Q: the process model and noise covariance
- B, u: Optionally, the control input and function

# Update Step